
package client.application;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Kundenverwaltung", targetNamespace = "http://application.server/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Kundenverwaltung {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://application.server/Kundenverwaltung/einfuegeKundeRequest", output = "http://application.server/Kundenverwaltung/einfuegeKundeResponse")
    public boolean einfuegeKunde(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://application.server/Kundenverwaltung/endeAnwendungRequest", output = "http://application.server/Kundenverwaltung/endeAnwendungResponse")
    public boolean endeAnwendung();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://application.server/Kundenverwaltung/getKundeZuNrRequest", output = "http://application.server/Kundenverwaltung/getKundeZuNrResponse")
    public String getKundeZuNr(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://application.server/Kundenverwaltung/getNaechsteKundenNrRequest", output = "http://application.server/Kundenverwaltung/getNaechsteKundenNrResponse")
    public int getNaechsteKundenNr();

}
