
package client.application;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KundenanfragenManagerService", targetNamespace = "http://application.server/", wsdlLocation = "http://localhost:18080/kundenverwaltung?wsdl")
public class KundenanfragenManagerService
    extends Service
{

    private final static URL KUNDENANFRAGENMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException KUNDENANFRAGENMANAGERSERVICE_EXCEPTION;
    private final static QName KUNDENANFRAGENMANAGERSERVICE_QNAME = new QName("http://application.server/", "KundenanfragenManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/kundenverwaltung?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KUNDENANFRAGENMANAGERSERVICE_WSDL_LOCATION = url;
        KUNDENANFRAGENMANAGERSERVICE_EXCEPTION = e;
    }

    public KundenanfragenManagerService() {
        super(__getWsdlLocation(), KUNDENANFRAGENMANAGERSERVICE_QNAME);
    }

    public KundenanfragenManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KUNDENANFRAGENMANAGERSERVICE_QNAME, features);
    }

    public KundenanfragenManagerService(URL wsdlLocation) {
        super(wsdlLocation, KUNDENANFRAGENMANAGERSERVICE_QNAME);
    }

    public KundenanfragenManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KUNDENANFRAGENMANAGERSERVICE_QNAME, features);
    }

    public KundenanfragenManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KundenanfragenManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Kundenverwaltung
     */
    @WebEndpoint(name = "KundenverwaltungPort")
    public Kundenverwaltung getKundenverwaltungPort() {
        return super.getPort(new QName("http://application.server/", "KundenverwaltungPort"), Kundenverwaltung.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Kundenverwaltung
     */
    @WebEndpoint(name = "KundenverwaltungPort")
    public Kundenverwaltung getKundenverwaltungPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://application.server/", "KundenverwaltungPort"), Kundenverwaltung.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KUNDENANFRAGENMANAGERSERVICE_EXCEPTION!= null) {
            throw KUNDENANFRAGENMANAGERSERVICE_EXCEPTION;
        }
        return KUNDENANFRAGENMANAGERSERVICE_WSDL_LOCATION;
    }

}
